In [34]:
import xarray as xr
import numpy as np

In [37]:
t = xr.open_mfdataset('temperature.nc')
t_df = t.to_dataframe()

In [10]:
p = xr.open_mfdataset('precipitation.nc')

In [26]:
p.precipitation.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
rel_hum = xr.open_mfdataset('relative_humidity.nc')

In [14]:
rel_hum.relative_humidity.values

array([[0.98179871, 0.97324455, 0.96136212, ..., 0.32149684, 0.29406649,
        0.34266466],
       [0.98044366, 0.9740575 , 0.96530521, ..., 0.32755858, 0.29211652,
        0.33950669],
       [0.96670586, 0.96022373, 0.95018935, ..., 0.36022612, 0.29112512,
        0.31717944],
       ...,
       [0.94528496, 0.95571285, 0.96315885, ..., 0.30854172, 0.24336775,
        0.21006376],
       [0.9438054 , 0.93615538, 0.95095032, ..., 0.26934421, 0.21466783,
        0.18350323],
       [0.94540215, 0.9364298 , 0.95676845, ..., 0.27180812, 0.20301874,
        0.16666947]])

In [15]:
wind_speed =  xr.open_mfdataset('wind_speed.nc')

In [28]:
wind_speed.wind_speed.values

array([[1.86200941, 1.88687003, 1.85235167, ..., 2.07917547, 2.84948754,
        2.4889133 ],
       [1.89076352, 1.90472603, 1.83580029, ..., 2.06559086, 2.88156915,
        2.59228516],
       [2.40567827, 2.53326917, 2.52224016, ..., 1.54751921, 1.79607666,
        1.89489043],
       ...,
       [2.60868907, 2.65035725, 2.52199125, ..., 0.60299808, 0.57838118,
        0.64265072],
       [2.35759854, 2.29862165, 2.1454525 , ..., 0.65515471, 0.81338978,
        0.66958487],
       [1.89428174, 1.7510196 , 1.86177754, ..., 0.87172973, 1.04955781,
        0.86811024]])

In [19]:
discharge =  xr.open_mfdataset('discharge.nc')

In [24]:
discharge.discharge.values

array([[39.1],
       [39.1],
       [38.5],
       ...,
       [27.3],
       [27.2],
       [27. ]])

In [21]:
 rad = xr.open_mfdataset('radiation.nc')

In [23]:
rad.global_radiation.values

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 27.26109123,  30.60818291,  34.25575256, ...,  48.55455017,
         53.35248947,  58.37289429],
       [184.79676819, 191.83575439, 199.74168396, ..., 249.40176392,
        256.53869629, 263.26556396],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])